config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'prototypes/popular#index'

  resources :user, only: [:index, :show, :new, :edit, :update]
  resources :login, only: :index
  resources :top, only: :index
  resources :prototypes do
    resources :comments, only: [:create], module: 'prototypes'
    resources :likes, only: [:create, :destroy]
  end
  resources :newest, only: :index, module: 'prototypes'
  resources :popular, only: :index, module: 'prototypes'
  resources :tags, only: [:index, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :thumbnails, dependent: :delete_all
  has_many :comments
  has_many :likes, dependent: :delete_all

  accepts_nested_attributes_for :thumbnails
  paginates_per 8

  acts_as_taggable
  acts_as_taggable_on :tags
end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :image, ThumbnailUploader
  enum property: %i(main sub)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prototypes
  has_many :comments
  has_many :likes, dependent: :delete_all

  validates :username, presence: true

  has_attached_file :avatar,
                      styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
                                      content_type: ["image/jpg","image/jpeg","image/png"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username, :group, :profile, :work, :avatar)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    @like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController

  before_action :authenticate_user!, only: [:create]
  before_action :get_prototype

  def create
    @prototype.comments.create(comments_params)
    @comments = @prototype.comments
  end

  private
  def comments_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id)
  end
  def get_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end

end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.order("prototypes.created_at desc").eager_load(:thumbnails, :user).page(params[:page])
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.page(params[:page]).eager_load(:thumbnails, :user).order("likes_count desc")
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :get_prototype, only: [:show, :edit, :update, :destroy]

  def index
  end
  def new
    @prototype = Prototype.new
    @prototype.thumbnails.build
  end

  def show
    @comments = @prototype.comments
    @comment = Comment.new
    @likes = Like.where(prototype_id: params[:id])
    @like = Like.find_by(user_id: current_user.id, prototype_id: params[:id]) if user_signed_in?
  end

  def create
    @prototype = Prototype.new(create_params)
    @prototype.save
    redirect_to :root
  end

  def edit
    @prototype.thumbnails.build
  end

  def update
    @prototype.update(update_params)
    redirect_to :root
  end

  def destroy
    @prototype.destroy
    redirect_to :root
  end


  private

  def get_prototype
    @prototype = Prototype.find(params[:id])
  end

  def create_params
    tag_list = params[:tag_list].join(",")
    params.require(:prototype).permit(:title, :concept, :catchcopy, :tag1, :tag2, :tag3, thumbnails_attributes: [:image, :property]).merge(user_id: current_user.id, tag_list: tag_list)
  end

  def update_params
    tag_list = params[:tag_list].join(",")
    params.require(:prototype).permit(:title, :concept, :catchcopy, :tag1, :tag2, :tag3, thumbnails_attributes: [:image, :property, :id]).merge(user_id: current_user.id, tag_list: tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @prototypes = Prototype.tagged_with(params[:id]).page(params[:page])
  end

  def index
    @tags = ActsAsTaggableOn::Tag.most_used(20)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes.order(created_at: :desc).page(params[:page])
  end

  def new
  end

  def edit
  end

  def update
    current_user.update(update_params)
    redirect_to :root
  end

  private
  def update_params
    params.require(:user).permit(:username, :group, :profile, :work, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototype_helper.rb
module PrototypeHelper
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", :alt => "PROTO TYPE - SHARE THE PROTOTYPE", :height => "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      //not login
      - unless current_user
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", new_user_session_path
      //login
      - if current_user
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.username
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "My Page", user_path(current_user)
              %li
                = link_to "Profile Edit", edit_user_path(current_user)
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto", new_prototype_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
.col-md-6.text-right
  - if @like.blank?
    %button.btn.btn-default.increment-button#like-button
      = link_to image_tag("icon_heart.svg"), prototype_likes_path(@prototype), method: :post, remote: true
      Like
      %span.num#like-sum
        = @likes.count
  - else
    %button.btn.btn-default.decrement-button#like-button
      = link_to image_tag("icon_heart_red.svg"), prototype_like_path(@prototype, @like), method: :delete, remote: true
      Like
      %span.num#like-sum
        = @likes.count

app/views/likes/create.js.erb
$('#like').html('<%= j render "likes/like" %>');
$('#like-sum').html('<%= @likes.count %>');

app/views/likes/destroy.js.erb
$('#like').html('<%= j render "likes/like" %>');
$('#like-sum').html('<%= @likes.count %>');

app/views/login/index.html.haml
.container
  %form.form-signin
    %h2.form-signin-heading Please sign in
    %label.sr-only{:for => "inputEmail"} Email address
    %input#inputEmail.form-control{:autofocus => "", :placeholder => "Email address", :required => "", :type => "email"}/
    %label.sr-only{:for => "inputPassword"} Password
    %input#inputPassword.form-control{:placeholder => "Password", :required => "", :type => "password"}/
    .checkbox
      %label
        %input{:type => "checkbox", :value => "remember-me"}/
        Remember me
    %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Sign in
  .text-center
    %p 
      Not a member? 
      %a{:href => "user/new"} Sign up now
      

app/views/prototypes/_comment.html.haml
.media
  .media-left
    = link_to image_tag(comment.user.avatar, {style: "width: 64px; height: 64px;", alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", class: "media-object"}), "users/#{comment.user.id}"
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.username
      %a.anchorjs-link{:href => "#top-aligned-media"}
        %span.anchorjs-icon
    %p= comment.text

app/views/prototypes/comments/create.js.erb
$('#comment_area #comment_list').html('<%=j render partial: "/prototypes/comment", collection: @comments %>');

app/views/prototypes/edit.html.haml
= form_for @prototype, html: { class: "container proto-new" } do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, placeholder: "Title", class: "proto-new-title"
    .row
      .col-md-12
        .cover-image-upload
          = f.fields_for :thumbnails, @prototype.thumbnails.main do |t|
            = t.file_field :image
            %img#main_preview{ src: @prototype.thumbnails.main.first!.image}
            = t.hidden_field :property, value: "main"
      .col-md-12
        %ul.proto-sub-list.list-group
          - f.object.thumbnails.sub.each_with_index do |sub, i|
            %li.list-group-item.col-md-4.sub_image_form.appear_form
              .image-upload{ id: "image_#{i}_uploader" }
                = f.fields_for :thumbnails, sub do |t|
                  = t.file_field :image
                  %img.sub_image{ id: "sub_#{i}_preview", src: t.object.image }
                  = t.hidden_field :property, value: "sub"
          - (f.object.thumbnails.sub.count..2).each do |i|
            %li.list-group-item.col-md-4.sub_image_form.hide_form
              .image-upload{id: "image_#{i}_uploader"}
                = f.fields_for :thumbnails, @thumbnail do |t|
                  = t.file_field :name
                  %img.sub_image{id: "sub_#{i}_preview"}
                  = t.hidden_field :property, value: "sub"
          - unless f.object.thumbnails.sub.count == 3
            %li.list-group-item.col-md-4.add_sub_image_form
              .image-upload-plus
                %span +
    .row.proto-description
      .col-md-12
        = f.text_field :catchcopy, placeholder: "Catch Copy"
      .col-md-12
        = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag 'tag_list[]', nil, placeholder: "Web Design"
          .col-md-3
            = text_field_tag 'tag_list[]', nil, placeholder: "UI"
          .col-md-3
            = text_field_tag 'tag_list[]', nil, placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"


:javascript
  $(function(){
    var $mainimg = $(".cover-image-upload input[type = file]");
    var $subimg0 = $("#image_0_uploader input[type = file]");
    var $subimg1 = $("#image_1_uploader input[type = file]");
    var $subimg2 = $("#image_2_uploader input[type = file]");
    var $addNewForm = $(".add_sub_image_form")
    var $hideForm = $(".hide_form")

    check_subimg(0)
    check_subimg(1)
    check_subimg(2)

    $mainimg.change(function(){
      proto_main_image(this)
    });

    $subimg0.change(function(){
      proto_sub_image(this, 0)
    });

    $subimg1.change(function(){
      proto_sub_image(this, 1)
    });

    $subimg2.change(function(){
      proto_sub_image(this, 2)
    });

    $addNewForm.click(function(){
      add_new_form_in_edit()
    });
  });

app/views/prototypes/index.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          %a{:href => "#"}
            %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", :style => "width: 64px; height: 64px;"}/
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
          .proto-user
            %a{:href => ""} by User
            %span.degree we-b inc. Designer
              
    .col-md-6.text-right
      %button.btn.btn-default
        = image_tag("icon_heart.svg")
        Like
        %span.num 20
  .row
    .col-md-9
      = image_tag("sample.png", :class => 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        %li.list-group-item
          = image_tag("sample.png", :class => 'img-responsive')
        %li.list-group-item
          = image_tag("sample.png", :class => 'img-responsive')
        %li.list-group-item
          = image_tag("sample.png", :class => 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p Type something
    .col-md-6
      %h4 Concept
      %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li 
          %a{:href => "#", :class => "btn btn-default"} iPad
        %li 
          %a{:href => "#", :class => "btn btn-default"} wireframe
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (10) 
    .col-md-8
      .media
        .media-left
          %a{:href => "#"}
            %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", :style => "width: 64px; height: 64px;"}/
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
            %a.anchorjs-link{:href => "#top-aligned-media"}
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      .media
        .media-left.media-middle
          %a{:href => "#"}
            %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", :style => "width: 64px; height: 64px;"}/
        .media-body
          %h4#middle-aligned-media.media-heading
            Middle aligned media
            %a.anchorjs-link{:href => "#middle-aligned-media"}
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      .media
        .media-left.media-bottom
          %a{:href => "#"}
            %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", :style => "width: 64px; height: 64px;"}/
        .media-body
          %h4#bottom-aligned-media.media-heading
            Bottom aligned media
            %a.anchorjs-link{:href => "#bottom-aligned-media"}
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      %form.form-inline{:role => "form"}
        %h4 Write a comment
        .row
          .form-group.col-md-10
            %textarea.form-control{:placeholder => "Your comments", :rows => "3"}
          .form-group.col-md-2
            %button.btn.btn-primary Comment
            

app/views/prototypes/newest/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ role: "presentation" }
          = link_to "Popular PROTO", root_path
        %li.active{ role: "presentation" }
          = link_to "Newest PROTO", newest_index_path
      = link_to "View Tags", "/", class: "btn btn-default col-lg-1"
.container.proto-list
  .row
    = render partial: "user/prototype", collection: @prototypes
.text-center
  %ul.pagination
    = paginate @prototypes

app/views/prototypes/popular/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          = link_to "Popular PROTO", root_path
        %li{ role: "presentation" }
          = link_to "Newest PROTO", newest_index_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"
.container.proto-list
  .row
    = render partial: "user/prototype", collection: @prototypes

.text-center
  %ul.pagination
    = paginate @prototypes

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag(@prototype.user.avatar, { :alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64",:style => "width: 64px; height: 64px;", class: "media-object"}), user_path(@prototype.user.id)
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "by #{@prototype.user.username}", user_path(@prototype.user.id)
            %span.degree= "#{@prototype.user.group} #{@prototype.user.work}"

    #like-function
      = render "likes/like"

  .row
    .col-md-9
      = image_tag(@prototype.thumbnails.main.first!.image, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.thumbnails.sub.each do |sub|
          %li.list-group-item
            = image_tag(sub.image, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p= @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tag_list.each do |tag|
          %li
            = link_to tag, tag_path(tag), :class  => "btn btn-default"

  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num= "(#{@comments.count})"
    .col-md-8#comment_area
      #comment_list
        = render partial: "comment", collection: @comments
      - if user_signed_in?
        = form_for @comment, html: { class: 'form-inline'},  url: prototype_comments_path(@prototype), remote: true do |f|
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :text, placeholder: "Your comments", rows: "3", class: "textform-control"
              = f.hidden_field :prototype_id, value: @prototype.id
            .form-group.col-md-2
              = f.submit "Comment", class: "btn btn-primary"

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tags list
      %ul
        - @tags.each do |tag|
          %li.col-md-4
            = link_to tag, tag_path(tag.name), class: "btn btn-default"

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", root_path
        %li{:role => "presentation"}
          = link_to "Newest PROTO", newest_index_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "/user/prototype", collection: @prototypes

.text-center
  %ul.pagination
    = paginate @prototypes

app/views/user/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == prototype.user_id
    .dropdown.drop_menu_location
      %button.btn.btn-default.dropdown-toggle#dropdownMenu{ type: "button", data: { toggle: "dropdown" } }
        Action
      %ul.dropdown-menu{ aria: { labelledby: "dropdownMenu1" } }
        %li
          = link_to "Delete", prototype_path(prototype), method: :delete
        %li
          = link_to "Edit", edit_prototype_path(prototype)
  .thumbnail
    = link_to image_tag(prototype.thumbnails.main.first!.image), prototype_path(prototype.id)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to "by #{prototype.user.username}", user_path(prototype.user.id)
        .proto-posted
          = prototype.created_at.strftime("%b %d")
      %ul.proto-tag-list.list-inline
        - prototype.tag_list.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: "btn btn-default"